### PR TITLE
Add random choice button

### PR DESCRIPTION
**Pull request by ZeroX-DG**
Surprisingly it somehow always give the worst suggestion 😂

### CODE REVIEW

**Comment by AlDrag** [comment]
@ZeroX-DG  Maybe the random choice button should actually click the button? Otherwise what's the point 😅

**Comment by ZeroX-DG** [comment]
I was thinking that too. But let's say if you have 4 choices but narrowed down to two specific one and the random choice button choose the wrong one. That'd be pretty frustrating.

**Comment by AlDrag** [comment]
Yea but you shouldn't be using the random choice button in that case haha, or maybe you should be able to select what to randomise.

Anyway, I don't mind too much, so I'm happy to merge this.

**Comment by ZeroX-DG** [comment]
Yeah there's no saying when user should or shouldn't use a feature. They'll do it anyway lol. Let's roll this out & get some user feedback.

**Pull request merged**
